%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
dataset_dir: /dataset/sequences/05
<<<<<<< HEAD
gt_files: /dataset/poses/05.txt
=======
>>>>>>> 7dee94b43ae6f7babddb0a8daa171c8fe297cc3a

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50
