name: Local runner test

on:
  workflow_dispatch:

jobs:
  testRunner:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3.6.0
      - name: build cmake
        run: mkdir build && cd build && cmake .. && make -j8
      - name: run test build
        run: ./bin/run_kitti_stereo
        
